Feature/unit testing go lang
ONSdigital/dp pull request #208
Opened 2021-08-02 13:29 UTC by outsidecoder

### What

Changes following PR.  I did git push and followed the instructions it gave me and it created a git challenge.

### How to review

Compare PR with previous commit.

### Who can review

Anyone.

2021-08-02 14:11 UTC, nshumoogum requested changes

2021-08-02 14:11 UTC, nshumoogum commented on training/unit-testing/go-lang/README.md
> +Note
Same note as above

2021-08-02 14:11 UTC, nshumoogum commented on training/unit-testing/go-lang/README.md
> +#### Writing SOLID Go
Think about adding extra whitespace between two headers

2021-08-02 14:21 UTC, outsidecoder commented on training/unit-testing/go-lang/README.md
> +Note
Thanks

2021-08-09 08:50 UTC, nshumoogum approved these changes

2021-08-24 08:57 UTC, merged